# Generated by Django 3.0.5 on 2020-05-01 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termine', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Parole',
            },
        ),
        migrations.CreateModel(
            name='Testo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=120)),
                ('link', models.URLField(blank=True, max_length=120, null=True)),
                ('privato', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestoParola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequenza', models.IntegerField()),
                ('parola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parola', to='AnalizzaVocabolario.Parola')),
                ('testo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testo', to='AnalizzaVocabolario.Testo')),
            ],
        ),
    ]
