# Generated by Django 3.0.6 on 2020-05-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalizzaVocabolario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testo',
            options={'verbose_name_plural': 'Testi'},
        ),
        migrations.AlterModelOptions(
            name='testoparola',
            options={'verbose_name_plural': 'TestoParole'},
        ),
        migrations.AddField(
            model_name='testo',
            name='IC',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='testo',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
