# Generated by Django 3.0.6 on 2020-05-19 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AnalizzaVocabolario', '0004_parolainblacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parolainblacklist',
            name='check',
        ),
        migrations.AddField(
            model_name='testo',
            name='data_creazione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
